'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace VSPTest
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CLOrderDetails", [Namespace]:="http://schemas.datacontract.org/2004/07/OOS.WCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CLOrderDetails
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FreightCostField As Decimal
        
        Private ItemsField() As VSPTest.CLOrderDetails.CLOrderItem
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ODGInvoiceNumberField As String
        
        Private OrderIdField As Integer
        
        Private OrderStatusField As VSPTest.CLOrderDetails.CLOrderStatus
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShipDateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShippingCarrierField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ShippingTrackingNumberField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FreightCost() As Decimal
            Get
                Return Me.FreightCostField
            End Get
            Set
                If (Me.FreightCostField.Equals(value) <> true) Then
                    Me.FreightCostField = value
                    Me.RaisePropertyChanged("FreightCost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Items() As VSPTest.CLOrderDetails.CLOrderItem()
            Get
                Return Me.ItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ItemsField, value) <> true) Then
                    Me.ItemsField = value
                    Me.RaisePropertyChanged("Items")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ODGInvoiceNumber() As String
            Get
                Return Me.ODGInvoiceNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ODGInvoiceNumberField, value) <> true) Then
                    Me.ODGInvoiceNumberField = value
                    Me.RaisePropertyChanged("ODGInvoiceNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property OrderId() As Integer
            Get
                Return Me.OrderIdField
            End Get
            Set
                If (Me.OrderIdField.Equals(value) <> true) Then
                    Me.OrderIdField = value
                    Me.RaisePropertyChanged("OrderId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property OrderStatus() As VSPTest.CLOrderDetails.CLOrderStatus
            Get
                Return Me.OrderStatusField
            End Get
            Set
                If (Me.OrderStatusField.Equals(value) <> true) Then
                    Me.OrderStatusField = value
                    Me.RaisePropertyChanged("OrderStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShipDate() As Date
            Get
                Return Me.ShipDateField
            End Get
            Set
                If (Me.ShipDateField.Equals(value) <> true) Then
                    Me.ShipDateField = value
                    Me.RaisePropertyChanged("ShipDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShippingCarrier() As String
            Get
                Return Me.ShippingCarrierField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShippingCarrierField, value) <> true) Then
                    Me.ShippingCarrierField = value
                    Me.RaisePropertyChanged("ShippingCarrier")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShippingTrackingNumber() As String
            Get
                Return Me.ShippingTrackingNumberField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ShippingTrackingNumberField, value) <> true) Then
                    Me.ShippingTrackingNumberField = value
                    Me.RaisePropertyChanged("ShippingTrackingNumber")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerStepThroughAttribute(),  _
         System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="CLOrderDetails.CLOrderItem", [Namespace]:="http://schemas.datacontract.org/2004/07/OOS.WCF"),  _
         System.SerializableAttribute()>  _
        Partial Public Class CLOrderItem
            Inherits Object
            Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
            
            <System.NonSerializedAttribute()>  _
            Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
            
            Private ItemCostField As Decimal
            
            Private ItemIdField As Integer
            
            Private ItemStatusField As VSPTest.CLOrderDetails.CLOrderItemStatus
            
            Private PRD_IDField As String
            
            Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
                Get
                    Return Me.extensionDataField
                End Get
                Set
                    Me.extensionDataField = value
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
            Public Property ItemCost() As Decimal
                Get
                    Return Me.ItemCostField
                End Get
                Set
                    If (Me.ItemCostField.Equals(value) <> true) Then
                        Me.ItemCostField = value
                        Me.RaisePropertyChanged("ItemCost")
                    End If
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
            Public Property ItemId() As Integer
                Get
                    Return Me.ItemIdField
                End Get
                Set
                    If (Me.ItemIdField.Equals(value) <> true) Then
                        Me.ItemIdField = value
                        Me.RaisePropertyChanged("ItemId")
                    End If
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
            Public Property ItemStatus() As VSPTest.CLOrderDetails.CLOrderItemStatus
                Get
                    Return Me.ItemStatusField
                End Get
                Set
                    If (Me.ItemStatusField.Equals(value) <> true) Then
                        Me.ItemStatusField = value
                        Me.RaisePropertyChanged("ItemStatus")
                    End If
                End Set
            End Property
            
            <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
            Public Property PRD_ID() As String
                Get
                    Return Me.PRD_IDField
                End Get
                Set
                    If (Object.ReferenceEquals(Me.PRD_IDField, value) <> true) Then
                        Me.PRD_IDField = value
                        Me.RaisePropertyChanged("PRD_ID")
                    End If
                End Set
            End Property
            
            Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
            
            Protected Sub RaisePropertyChanged(ByVal propertyName As String)
                Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
                If (Not (propertyChanged) Is Nothing) Then
                    propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
                End If
            End Sub
        End Class
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="CLOrderDetails.CLOrderStatus", [Namespace]:="http://schemas.datacontract.org/2004/07/OOS.WCF")>  _
        Public Enum CLOrderStatus As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Cancelled = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Hold = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            InProcess = 2
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Backordered = 3
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Shipped = 4
        End Enum
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="CLOrderDetails.CLOrderItemStatus", [Namespace]:="http://schemas.datacontract.org/2004/07/OOS.WCF")>  _
        Public Enum CLOrderItemStatus As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Cancelled = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Hold = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            InProcess = 2
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Backordered = 3
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Shipped = 4
        End Enum
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateOrderStatusResponse", [Namespace]:="http://schemas.datacontract.org/2004/07/OOS.WCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateOrderStatusResponse
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DetailedMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsSuccessField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusCodeField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DetailedMessage() As String
            Get
                Return Me.DetailedMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DetailedMessageField, value) <> true) Then
                    Me.DetailedMessageField = value
                    Me.RaisePropertyChanged("DetailedMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsSuccess() As Boolean
            Get
                Return Me.IsSuccessField
            End Get
            Set
                If (Me.IsSuccessField.Equals(value) <> true) Then
                    Me.IsSuccessField = value
                    Me.RaisePropertyChanged("IsSuccess")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusCode() As Integer
            Get
                Return Me.StatusCodeField
            End Get
            Set
                If (Me.StatusCodeField.Equals(value) <> true) Then
                    Me.StatusCodeField = value
                    Me.RaisePropertyChanged("StatusCode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.acumenex.com/2011/01/odg", ConfigurationName:="VSPTest.ODGOrderStatusService")>  _
    Public Interface ODGOrderStatusService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.acumenex.com/2011/01/odg/ODGOrderStatusService/UpdateOrderStatus", ReplyAction:="http://schemas.acumenex.com/2011/01/odg/ODGOrderStatusService/UpdateOrderStatusRe"& _ 
            "sponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(String), Action:="http://schemas.acumenex.com/2011/01/odg/ODGOrderStatusService/UpdateOrderStatusSt"& _ 
            "ringFault", Name:="string", [Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/")>  _
        Function UpdateOrderStatus(ByVal orderDetails As VSPTest.CLOrderDetails, ByVal passPhrase As String) As VSPTest.UpdateOrderStatusResponse
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ODGOrderStatusServiceChannel
        Inherits VSPTest.ODGOrderStatusService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ODGOrderStatusServiceClient
        Inherits System.ServiceModel.ClientBase(Of VSPTest.ODGOrderStatusService)
        Implements VSPTest.ODGOrderStatusService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function UpdateOrderStatus(ByVal orderDetails As VSPTest.CLOrderDetails, ByVal passPhrase As String) As VSPTest.UpdateOrderStatusResponse Implements VSPTest.ODGOrderStatusService.UpdateOrderStatus
            Return MyBase.Channel.UpdateOrderStatus(orderDetails, passPhrase)
        End Function
    End Class
End Namespace
