'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4016
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4016.
'
Namespace scannerService
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_IScannerService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ScannerService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://odgiisvm.opticaldg.com:8080/ScannerService/ScannerService.svc"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IScannerService/GetItemInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetItemInfo(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal itemUpcCode As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal whseCode As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetItemInfo", New Object() {itemUpcCode, whseCode})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetItemInfo(ByVal itemUpcCode As String, ByVal whseCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetItemInfo", New Object() {itemUpcCode, whseCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetItemInfo(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IScannerService/CheckBin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckBin(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal binNo As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("CheckBin", New Object() {binNo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginCheckBin(ByVal binNo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("CheckBin", New Object() {binNo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndCheckBin(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IScannerService/GetBin", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetBin(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal itemUpcCode As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetBin", New Object() {itemUpcCode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginGetBin(ByVal itemUpcCode As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetBin", New Object() {itemUpcCode}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetBin(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IScannerService/IsBinValid", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsBinValid(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal itemUpcCode As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal whse As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("IsBinValid", New Object() {itemUpcCode, whse})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginIsBinValid(ByVal itemUpcCode As String, ByVal whse As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("IsBinValid", New Object() {itemUpcCode, whse}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndIsBinValid(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IScannerService/GetScanData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetScanData(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal binNo As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> System.Data.DataSet
            Dim results() As Object = Me.Invoke("GetScanData", New Object() {binNo})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginGetScanData(ByVal binNo As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetScanData", New Object() {binNo}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetScanData(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IScannerService/UpdateItemInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateItemInfo(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal dst As System.Data.DataSet, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal binNo As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal priceCatgy As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal operId As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal whseCode As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal forUpdate As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("UpdateItemInfo", New Object() {dst, binNo, priceCatgy, operId, whseCode, forUpdate})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginUpdateItemInfo(ByVal dst As System.Data.DataSet, ByVal binNo As String, ByVal priceCatgy As String, ByVal operId As String, ByVal whseCode As String, ByVal forUpdate As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateItemInfo", New Object() {dst, binNo, priceCatgy, operId, whseCode, forUpdate}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndUpdateItemInfo(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IScannerService/LoadPO", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LoadPO(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal invPackUPC As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> System.Data.DataSet
            Dim results() As Object = Me.Invoke("LoadPO", New Object() {invPackUPC})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginLoadPO(ByVal invPackUPC As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("LoadPO", New Object() {invPackUPC}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndLoadPO(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IScannerService/UpdatePO", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdatePO(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal WH_OPER_ID As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal dst As System.Data.DataSet) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("UpdatePO", New Object() {WH_OPER_ID, dst})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginUpdatePO(ByVal WH_OPER_ID As String, ByVal dst As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdatePO", New Object() {WH_OPER_ID, dst}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndUpdatePO(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
